from checkmate import checkmate

def main():
    # เคสนี้ต้อง Success เพราะ Pawn อยู่ "ข้างล่าง" ของ King (แถว 5 vs แถว 4)
    board = """\
.........
.........
.........
....K....
....P....
......B..
.........
.........
...R....."""
    checkmate(board)

if __name__ == "__main__":
    main()